### PR TITLE
update to 19w05a

### PR DESCRIPTION
**Pull request by MelanX**

### CODE REVIEW

**Comment by shedaniel** [comment]
Are you sure that it is updated to 19w05a? The CI couldn't compile

**Comment by MelanX** [comment]
Unfortunally no. I haven't tested, I just thought it needs an update because 19w04a needed one 😅 I'm sorry! Just wanted to speed up the compatibility with newer versions :c I didn't think enough before this.

**Comment by shedaniel** [comment]
It's okay, I will do this if REI is not compatible (I haven't tested)

**Comment by shedaniel** [comment]
Confirmed that the current version works on 19w05a

**Pull request closed without merging**
