### PR TITLE
Added workstation usage info when looking for usage of item/block

### LINKED ISSUE #218: [Feature] Allow the usage menu (U) to show what recipes you can make with a block (eg furnace)
**Describe the solution you'd like**
Currently you can only see the recipes that a furnace can do by pressing the crafting arrow in the GUI of the furnace or pressing R on the end product.

I think it would be way more intuitive to show recipes of a block alongside the recipe of itself. JEI had this and it's how many (or atleast me) used to access the list a craftables a block that a thing can do. 

Also it allows mods which don't have that clickable crafting arrow thing integrated to have an easy to access the blocks recipes without diving through submenus

### PR DESCRIPTION
**Pull request by vhd**
Close #218
Запись экрана 2019-12-23 в 13 15 30 3

### CODE REVIEW

**Comment by shedaniel** [comment]
I would like to make non workstation recipes show in front of the ones that is added because of work stations.

**Comment by vhd** [comment]
I was thinking about this, but haven't found any of real-world case scenarios where it would be necessary.

**Comment by shedaniel** [comment]
maybe an recipe require a crafting table like crafting stations

**Comment by vhd** [comment]
I can see it now. Yeah! That was pretty annoying in JEI.
But i can't figure now to do such behavior :(

**Comment by shedaniel** [comment]
Don't worry this pr is good enough, I will merge it later, thanks for contributing!

**Pull request merged**
